### ISSUE TITLE
Warnings during homer_installer.sh

### ISSUE THREAD

**Issue by SB-JohnK** [sipcapture/homer-installer#64]
I noticed some database related errors when I run homer_installer.sh

OS is CentOS Linux release 7.6.1810 (Core), Fresh install.

migration file "20190401143156_Datastructure.js" failed
migration failed with error: create table "users" ("id" serial primary key, "username" varchar(50) not null, "partid" integer not null default '10', "email" varchar(250) not null, "firstname" varchar(50) not null, "lastname" varchar(50) not null, "department" varchar(50) not null default 'NOC', "usergroup" varchar(250) not null, "hash" varchar(128) not null, "guid" varchar(50) not null, "created_at" timestamptz not null default CURRENT_TIMESTAMP) - relation "users" already exists
error: relation "users" already exists
    at Connection.parseE (/opt/homer-app/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/opt/homer-app/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/opt/homer-app/node_modules/pg/lib/connection.js:113:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Using environment: development
error: relation "agent_location_session" does not exist
    at Connection.parseE (/opt/homer-app/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/opt/homer-app/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/opt/homer-app/node_modules/pg/lib/connection.js:113:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by aqsyonas** [comment]
@SB-JohnK looks like you ran the script multiple times? Script is complaining about already existing `users` table.

**Comment by SB-JohnK** [comment]
I only ran the script a single time.

I can re-produce this 100% of the time.,

Create new VM
Install Centos 7 from iso
yum install epel-release wget redhat-lsb-core curl git 
wget https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh
chmod +x installer
run installer

I get the migration errors every time. 

[homer_installer.sh.3574.log](https://github.com/sipcapture/homer-installer/files/3611960/homer_installer.sh.3574.log)

**Comment by aqsyonas** [comment]
@SB-JohnK thanks. I will check that.

**Comment by aqsyonas** [comment]
@SB-JohnK unfortunately, I could not replicate above issue, I have tried your instructions on freshly installed centos7 and it worked for me. Even your log does not have anything anomalous.

**Comment by aqsyonas** [comment]
closing due to no response. Please open if the issue still persists for you.
